apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Values.meta.instance }}
    app.kubernetes.io/version: {{ .Values.docker.tag }}
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
    stage: {{ .Values.meta.stage }}
    owner: {{ .Values.meta.owner }}
spec:
  replicas: {{ .Values.infra.scaling.startReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Values.meta.instance }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Values.meta.instance }}
        app.kubernetes.io/version: {{ .Values.docker.tag }}
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: helm
        stage: {{ .Values.meta.stage }}
        owner: {{ .Values.meta.owner }}
    spec:
      containers:
      - image: {{ .Values.docker.registry }}/{{ .Values.docker.image }}:{{ .Values.docker.tag }}
        name: web
        ports:
        - containerPort: {{ .Values.appConfig.port }}
          name: http
        volumeMounts:
        - name: config
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.appConfig.port }}
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.appConfig.port }}
        resources:
          requests:
            cpu: {{ .Values.infra.resources.requests.cpu }}
            memory: {{ .Values.infra.resources.requests.memory }}
          limits:
            cpu: {{ .Values.infra.resources.limits.cpu }}
            memory: {{ .Values.infra.resources.limits.memory }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-config

